# -*- coding: UTF-8 -*-
from langdetect import detect
import time

text = u"""<figure>
<img src="http://cdn.theatlantic.com/assets/media/img/mt/2016/02/RTXX2VZ/lead_large.jpg" style="max-width:100%;"/>
<figcaption> <cite>Reuters</cite></figcaption>
</figure>
<p dir="ltr"><span><span>Justice Antonin Scalia, more than any other Supreme Court justice, set the parameters for the constitutional debates of this era. The sharpness of his mind and the rigor of his jurisprudence were regularly on display up until his passing. As those of us fortunate enough to have directly engaged with him in recent years can attest, up until his last breath, there was no indication that he had dulled in his ability to navigate the incredible intellectual challenges that were his job description.</span></span></p>
<p dir="ltr"><span><span>By working until the age of 79, Scalia had surpassed by a decade and a half the typical retirement age for an American worker, but his mental longevity was no exception: The typical Supreme Court justice does not hang up his or her robe until reaching the age of nearly 80. At 82, Justice Ruth Bader Ginsburg remains at the peak of her powers and serves as the leading voice for the so-called liberal wing of the Court, as did Justice John Paul Stevens up until his retirement at 90.<a href="http://www.theatlantic.com/business/archive/2016/02/supreme-court-justices-mental-sharpness/470175/#anchor%201">*</a></span></span></p>
<p dir="ltr"><span><span>Are Supreme Court justices possessed with some sort of superhuman mental resilience (perhaps one that explains how they got to where they are) that allows them special cognitive longevity? Or have they simply lucked into avoiding the sorts of cognitive decline that afflict so many others their age? The answers to these questions have implications far beyond this specialized group of nine, and will only grow in importance as the U.S. workforce ages. The answers also demonstrate that America’s legal structures for addressing age discrimination are, in important respects, out of step with the accepted neurological understanding of aging.  </span></span></p>
<p dir="ltr"><span><span>When it comes to maintaining cognitive abilities into old age, research suggests that a variety of factors are at play. The standard account of aging’s effect on cognitive functioning distinguishes between </span><a href="http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4086863/"><span>“fluid” and “crystallized”</span></a><span> intelligence. Fluid intelligence—the ability to think and reason independent of prior knowledge—diminishes as we age. </span>As <a href="http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2683339/">early as our </a></span><a href="http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2683339/">20s</a><span>, (or </span><a href="http://pss.sagepub.com/content/early/2015/03/06/0956797614567339.abstract" target="_blank">even earlier</a><span> for some tasks), </span><span><span>we can begin to experience a slow but increasing decline in the fluid aspects of our cognitive functioning, such as mental processing speed, working memory, attention span, and abstract problem-solving skills. By contrast, crystallized intelligence—the ability to draw on and apply one’s accumulated experience and knowledge—increases as we age, generally </span><a href="http://www.sciencedirect.com/science/article/pii/0887617795000038"><span>plateauing until sometime in our 60s</span></a><span> and falling thereafter. In other words, the science confirms common experience: As we age, we gain wisdom within our range of expertise, but slow in our ability to operate effectively outside our comfort zone.</span></span></p>
<p dir="ltr"><span><span>But what does the inevitable deterioration of fluid intelligence mean in terms of the ability to work into the golden years? The answer, unsatisfyingly, defies easy generalization. First, all humans approach the starting blocks of the race against time with different cognitive baselines. As Ian Deary, the director of the Centre for Cognitive Ageing at the University of Edinburgh, </span><a href="https://bmb.oxfordjournals.org/content/92/1/135.full"><span>writes</span></a><span>, “Of the many possible contributors to cognitive ability level in old age, none yet known approaches the effect size of mental ability measured in childhood.” To put it simply, smart kids generally make for smart seniors.</span></span></p>
<p dir="ltr"><span><span>Second, the risk that one will suffer a neurological disorder that severely disrupts cognitive functioning increases dramatically as people age. The risk of stroke, for example, </span><a href="http://www.strokeassociation.org/STROKEORG/AboutStroke/UnderstandingRisk/Understanding-Stroke-Risk_UCM_308539_SubHomePage.jsp"><span>doubles each decade after age 55</span></a><span>. The odds are equally unforgiving for Alzheimer’s, with the odds </span><a href="http://www.alz.org/research/science/alzheimers_disease_causes.asp"><span>doubling every five years after age 65</span></a><span>. The ability to remain productive as a person ages is therefore tied to the ever-increasing chance that his or her number will come up in the grim lottery of cognitive disease.</span></span></p>
<p dir="ltr"><span><span>Research does </span><a href="http://www.ncbi.nlm.nih.gov/pubmed/23079557"><span>show</span></a><span>, however, that e</span></span><span><span>ngaging in high levels of cognitive activity from childhood to middle age builds up a “cognitive reserve” that protects against the deterioration of mental functioning. This reserve inevitably dissipates as people age, but its effects can be long-lasting. Older people who continue to engage in mentally stimulating activities that require them to interact with and process information—such as reading the newspaper or playing chess—experience </span><a href="http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2942032/"><span>dramatically slower rates of cognitive decline than their idle peers.</span></a><span> It should therefore come as no surprise that retirement represents </span><a href="https://www.researchgate.net/publication/224854681_Does_Retirement_Affect_Cognitive_Functioning"><span>a crucial setback</span></a><span> in the battle to stay mentally fit, often prompting significant and sudden cognitive deterioration. </span><a href="http://www.ncbi.nlm.nih.gov/pubmed/24791704"><span>One longitudinal study </span></a><span>of nearly half a million people found that each additional year of delayed retirement reduces the risk of dementia </span><a href="http://www.nbcnews.com/health/delaying-retirement-can-delay-dementia-large-study-finds-6C10637029"><span>by 3.2 percent</span></a><span>. Similar results </span><a href="https://www.researchgate.net/publication/272795810_Retirement_Age_and_the_Age_of_Onset_of_Alzheimer%27s_Disease_Results_from_the_ICTUS_Study"><span>have been found for Alzheimer’s</span></a><span>. And </span><a href="http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3772831/"><span>a recent study</span></a><span> that examined brain autopsies shows that these effects occur even in people who have experienced the types of physical damage to their brains ordinarily associated with dementia and other neurological disorders—which suggests that continued mental stimulation leads to enhanced cognitive functioning, and not the other way around.</span></span></p>
<p dir="ltr"><span><span>Mentally stimulating work, it should be noted, is not by any means limited to white-collar jobs. Researchers have observed improvements in brain structure associated with higher cognitive functioning resulting from activities as diverse as </span><a href="http://www.ncbi.nlm.nih.gov/pubmed/16763039"><span>studying for a medical-school exam</span></a><span> and </span><a href="http://www.ncbi.nlm.nih.gov/pmc/articles/PMC18253/"><span>apprenticing as a London taxi driver</span></a><span>.</span></span></p>
<p dir="ltr"><span><span>Two lessons, then, can be drawn from the research. First, for those professions in which crystallized intelligence is more valuable than fluid intelligence, the business case for a mandatory changing of the guard would seem thin. Second, since retirement actually can stimulate early cognitive decline, forcing people to retire on the expectation that their productive years are almost through can be a self-fulfilling prophecy.</span></span></p>
<p dir="ltr"><span><span>Does the legal framework for regulating the relationship between aging and work reflect these lessons? Yes and no.</span></span></p>
<p dir="ltr"><span><span>A 1967 federal statute, the Age Discrimination and Employment Act, or ADEA, </span><a href="http://www.eeoc.gov/laws/statutes/adea.cfm"><span>generally prohibits</span></a><span> employers from discriminating against older workers based on their age—with the law’s protections kicking in at the ripe young age of 40. </span></span></p>
<p dir="ltr"><span><span>As with any rule, however, the ADEA is in large part defined by its exceptions, perhaps the most significant of which excludes from coverage people employed in positions “where age is a bona fide occupational qualification.” In other words, Congress recognized that, for some jobs at least, age discrimination just plain makes sense.</span></span></p>
<p dir="ltr"><span><span>This seems uncontroversial enough in theory, but decades later, courts are still fumbling through the process of deciding which jobs the exception should cover. For example, in 2006, the federal agency charged with enforcing the ADEA, the Equal Employment Opportunity Commission (EEOC), </span><a href="http://www.ca5.uscourts.gov/opinions%5Cunpub%5C13/13-10164.0.pdf"><span>sued ExxonMobil</span></a><span> for requiring the pilots of its corporate jets to retire when they turned 60. A federal appeals court disagreed with the EEOC, holding that ExxonMobil’s policy is reasonable given the greater likelihood that a heart attack or stroke might suddenly incapacitate older pilots. The court further pointed to the Federal Aviation Administration’s comparable age-60 cutoff for commercial pilots (which has since been raised to 65). The FAA justified the age restriction based on its determination that aging causes general deterioration in not only pilots’ physical stamina, but also measures of their fluid intelligence, such as the “ability to perform highly skilled tasks rapidly” and “to learn new techniques, skills, and procedures.”</span></span></p>
<p><span><span>Pilots are uniquely good exemplars of the tradeoffs between youth and experience. On the one hand, piloting an aircraft requires both prolonged focus and, in times of crisis, the swift execution of complex maneuvers. Yet it is also a skill-based trade in which one prefers the steady, experienced hand to one that is energetic but green. Here again, common sense is vindicated by the data: Accident rates </span><a href="https://www.faa.gov/data_research/research/med_humanfacs/age60/media/age60_3.pdf"><span>are highest</span></a><span> among pilots younger than 30 and older than 60, with pilots in their 40s providing the most reliable rides. The same U-shaped curve is seen when plotting the relationship between age and </span><a href="http://www.ncbi.nlm.nih.gov/pubmed/7718080"><span>car accidents</span></a><span>.</span></span></p>
<hr/><p><strong><big>Commercial Pilots’ Accident Rates, by Age</big></strong></p>
<figure><img alt="" src="https://cdn.theatlantic.com/assets/media/img/posts/2016/02/Screen_Shot_2016_02_19_at_11.23.28_AM/609e506a1.jpg" style="max-width:100%;"/><figcaption class="credit">FAA</figcaption></figure><hr/><p dir="ltr"><span><span>The law’s treatment of pilots suggests that the ADEA, as implemented by the courts, might succeed in reaching a sensible balance between protecting older workers from discrimination and accounting for the unfortunate realities of aging. However, a second major exception to the law’s protections, which excludes “bona fide executives and high policymakers,” is less sensible. Congress presumably decided to exclude “executives” and workers “in a high policymaking position” from protection against age discrimination because it figured that these categories of employees are not especially vulnerable and can fend for themselves. That may well be true, but they are also the most likely to occupy the types of positions in which crystallized intelligence is especially valuable. Forcing executives and policymakers into early retirement may therefore be a particularly irrational form of age discrimination. </span></span></p>
<p dir="ltr"><span class="s1">Which connects back to Scalia, whose passing was not unusual given his physical health, but was abrupt given his mental sharpness.</span><span><span> A judge is a prime example of the type of worker for whom wisdom matters more than more fluid markers of intelligence. Yet when the Supreme Court considered the lawfulness of mandatory retirement ages for judges, in a 1991 case known as <em>Gregory v. Ashcroft</em></span><span>, it had little trouble justifying the use of age cutoffs. </span></span></p>
<p dir="ltr"><span><span>While federal judges enjoy life tenure under Article III of the Constitution, a majority of states force their judges to retire after they reach a certain age, most often 65 or 70. Judge Ellis Gregory Jr., a Missouri judge who was 63 by the time his case made it to the Supreme Court, challenged Missouri’s mandatory-retirement age, claiming it violated both the ADEA and the Equal Protection Clause of the Constitution, which requires that the government have a “rational basis” for engaging in overt age discrimination of the kind practiced against Missouri judges. </span></span></p>
<p dir="ltr"><span><span>I recently spoke to Gregory about his reasons for bringing the lawsuit. Clear-eyed and articulate at 88, he emphasized the value of crystallized intelligence in his chosen profession: “After you’ve served on the bench for a number of years, you gain a great deal of knowledge and experience, and that is borne out in your abilities as a judge,” Gregory explained. He continued, “It is a shame, a waste of judicial experience, for an arbitrary age limit to stop a judge from contributing if the judge has good health and is otherwise able to continue on.” </span></span></p>
<p dir="ltr"><span><span>The Supreme Court disagreed. Speaking </span><a href="https://www.law.cornell.edu/supct/html/90-50.ZO.html"><span>through Justice Sandra Day O’Connor</span></a><span>, the modern judiciary’s ultimate pragmatist, the Court upheld Missouri’s age restriction as consistent with both the ADEA and the Constitution’s Equal Protection Clause. With respect to the ADEA, the Court held that judges are excluded from the law’s coverage because they are on the “policy-making </span><span>level</span><span>” (the relevant standard under the ADEA for state officials) even if they are not “policy makers” per se. </span></span></p>
<p dir="ltr"><span><span>On the broader question of the constitutionality of Missouri’s mandatory retirement age, the Court reasoned that forcing judges into retirement at 70 is justified by Missouri’s “legitimate, indeed compelling, interest in maintaining a judiciary fully capable of performing the demanding tasks that judges must perform.”  Without citing any social, empirical, or scientific authority, O’Connor applied her common-sense wisdom to determine that mandatory retirement ages reflect the “unfortunate fact of life that physical and mental capacity sometimes diminish with age.” </span></span></p>
<p dir="ltr"><span><span>Later in her opinion, she hedges on this crucial point, writing, “It is far from true that all judges suffer significant deterioration in performance at age 70. It is probably not true that most do. It may not be true at all.” But such laws are nevertheless rational, she concluded, because they “avoid the tedious and often perplexing decisions to determine which judges after a certain age are physically and mentally qualified and those who are not.” In short, “the people of Missouri rationally could conclude that the threat of deterioration at age 70 is sufficiently great, and the alternatives for removal sufficiently inadequate” that Missouri’s age discrimination against older judges is a necessary evil. (As for Gregory, the blow of losing his appeal was softened when, after his mandatory retirement at age 70, he was appointed by the Missouri Supreme Court as a senior judge. In that capacity, he continued to regularly hear cases for more than a decade.)</span></span></p>
<p dir="ltr"><span><span>The Court’s decision in <em>Gregory v. Ashcroft</em> is extraordinary for a number of reasons, not least of which is the oddity of a Court filled with people engaged in the same basic job as Gregory—just more important—telling their fellow judges that it is only sensible that they leave the judging to a younger generation. (Compounding the irony, four of the justices were then over 70, and all but one, Justice David Souter, would retire well past their 70th birthdays. It is perhaps little surprise that the oldest members of the Court, Justices Thurgood Marshall and Harry Blackmun, then both 82, were the only dissenters from the Court’s decision.)  </span></span></p>
<p dir="ltr"><span><span>Perhaps in recognition of this awkward dynamic, the Court refused to declare firmly that older judges often, or even ever, suffer diminished abilities. But in pointing to the “tedious” and “perplexing” process of discerning which older judges can no longer cut it, the Court seemed to elevate an interest in avoiding difficult conversations over the constitutional right to be free from arbitrary age discrimination. For those judges who, like Scalia, remain fully fit for office throughout their 70s and beyond, it would seem a cruel excuse that their productive years must come to an artificial halt because age might have caught up with some of their peers, and because a bright-light rule is easier to administer. </span></span></p>
<p dir="ltr"><span><span>Supreme Court justices generally evolve during their time on the Court. While these evolutions are most apparent when a justice’s views swing toward the other side of the Court’s internal ideological spectrum, in Scalia’s case, it </span><a href="http://www.theatlantic.com/politics/archive/2016/02/what-made-antonin-scalia-great/462837/"><span>has been observed</span></a><span> that the firmness of his convictions appeared to solidify during his fourth decade on the bench. Judgment of a justice’s evolution tends to be dictated by whether or not ideological developments bring the justice’s views closer to that of the person doing the assessing. But the fact this evolution occurs at all serves as evidence that judging is a craft like any other, one that is honed through the accumulation of knowledge and experience.</span></span></p>
<p dir="ltr"><span><span>Judges are not pilots. Society vests them with the power to turn their judgments into law based on its faith in their wisdom, integrity and intuition, all of which are forged over a lifetime. Many of Scalia’s most consequential opinions—from his majority opinion in </span><a href="http://www.supremecourt.gov/opinions/07pdf/07-290.pdf"><em><span>District of Columbia v. Heller</span></em><span> </span></a><span>interpreting the Second Amendment as an individual right, to his blistering dissent in </span><em><a href="http://www.supremecourt.gov/opinions/14pdf/14-556_3204.pdf"><span>Obergefell v. Hodges</span></a></em><span> objecting to the Court’s recognition of the constitutional right to same-sex marriage—were authored well past his 70th birthday.    </span></span></p>
<p dir="ltr"><span><span>Whether or not one agrees with the views expressed in these opinions—and I do not—Scalia’s contributions late in life are a reminder that the legal structures in the United States for addressing age discrimination do not always accurately reflect the relationship between age and ability. No doubt there are professions and pastimes for which age is a legitimate exclusionary bar, and no doubt there are many from whom time has robbed too much. But age discrimination should be justified by a legitimate, evidence-based connection between age and ability, and even then only permitted when an age-discriminatory measure is sufficiently tailored to avoid harming more than it helps. </span></span></p>
<p dir="ltr"><span><span>When Scalia joined the Court’s opinion in </span><span>Gregory</span><span>, he was, at 55, the Court’s second-youngest justice. Yet one wonders whether he might have felt differently about the rationality of a mandatory retirement age for judges at a later point in his life.</span></span></p>
<hr/><p><em><small><a id="anchor 1" name="anchor%201">* </a>This article originally stated that Ruth Bader Ginsburg is 83. We regret the error.</small></em></p>
<img alt="" src="http://feeds.feedburner.com/~r/TheAtlantic/~4/CmadyrQzCEI" style="max-width:100%;"/>"""

start = time.time()
lang = detect(text)
end = time.time()
print(lang)
print('Time: {0}'.format(end-start))
